Hometask1
Alexzim147/smart-home-2021 pull request #1
Opened 2021-03-10 20:48 UTC by Alexzim147

2021-03-16 06:03 UTC, a-ivanov requested changes

2021-03-16 06:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/EventProcessingCycle.java
> +                LightEventProcessing lightEventProcessing = new LightEventProcessing(event, smartHome);
DIP: передавайте готовые инстансы через конструктор.

2021-03-16 06:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/EventProcessingCycle.java
> +    private static SensorEvent getNextSensorEvent() {
SRP: отдельная ответственность.

2021-03-16 06:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/DoorEventProcessing.java
> +                        if (room.getName().equals("hall")) {
SRP: отдельная ответственность в отдельном классе.

2021-03-17 17:34 UTC, Alexzim147 commented
Исправил ошибки.

2021-03-18 05:06 UTC, a-ivanov approved these changes

2021-03-18 05:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventProcessing> eventProcessings = new ArrayList<>(Arrays.asList(
`List` объявляйте переменные типом интерфейса.

2021-03-24 16:34 UTC, merged